openapi: 3.0.3
info:
  title: CooperativePixelArt gateway API
  description: |-
    This is the API of the PixelArtUser gateway
  # termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
# externalDocs:
#  description: Find out more about Swagger
#  url: http://swagger.io
servers:
  - url: https://localhost:9000/api
tags:
  - name: pixel-grid
    description: Operations about the pixel grids
    # externalDocs:
    #  description: Find out more
    #  url: http://swagger.io
paths:
  /pixel-grids:
    get:
      tags:
        - "pixel-grid"
      summary: Get the current pixel-grids (ids)
      description: ''
      operationId: getCurrentPixelGrids
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /pixel-grids/{gridIds}:
    get:
      tags:
        - pixel-grid
      summary: Get the current state of the pixel grid
      description: ''
      operationId: getPixelGridState
      parameters:
      - name: gridIds
        in: path
        description: The pixel-grid id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PixelGrid'
        '500':
          description: Service internal error

  /pixel-grids/{gridIds}/color-pixel/{color}:
    post:
      tags:
        - pixel-grid
      summary: Select (paint) the pixel selcted
      description: ''
      operationId: selectPixel
      parameters:
        - name: gridIds
          in: path
          description: The pixel-grid id
          required: true
          schema:
            type: string
        - name: color
          in: path
          description: The color to paint the pixel
          required: true
          schema:
            type: integer
      requestBody:
        description: The destination point
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Point'
      responses:
        '200':
          description: successful operation
        '400':
          description: invalid parameter supplied
        '500':
          description: service internal error
components:
  schemas:
    Point:
      type: object
      required:
      - x
      - y
      properties:
        x:
          type: integer
        y:
          type: integer
    PixelGrid:
      type: object
      required:
      - numColumns
      - numRows
      - pixels
      properties:
        numColumns:
          type: integer
        numRows:
          type: integer
        pixel:
          type: array
          items:
            type: integer

